# Generated by Django 3.1.7 on 2021-06-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentQuiz', '0003_finalresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qprovidemanswer',
            options={'verbose_name_plural': 'Answers'},
        ),
    ]
