# Generated by Django 3.1.7 on 2021-06-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentQuiz', '0004_auto_20210626_0445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QProvideMAnswer',
            new_name='Answer',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
    ]
