# Generated by Django 3.1.7 on 2021-06-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('photo', models.ImageField(default='SFaceRecognize/FRStream/Datasets/opencv_frame_0.png', upload_to='detected/')),
                ('std_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.students')),
            ],
        ),
    ]
