# Generated by Django 3.1.7 on 2021-06-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFaceRecognize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected',
            name='photo',
            field=models.ImageField(default='SFaceRecognize/FRStream/detected/opencv_frame_0.png', upload_to='detected/'),
        ),
    ]
